meta:
  event_codes:
preproc:
  - apply_gradient_compensation: {grade: 3}
  - notch_filter:       {freqs: 60 120, phase: 'minimum'}
  - filter:             {l_freq: 1, h_freq: 50, phase: 'minimum'}
  - resample:           {sfreq: 100, method: 'polyphase'}
