# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/gpt2megmix/model.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/omega/gpt2megmix
resume_from: null

model_name: GPT2MEGMix
loss_name: CrossEntropy
eval_class: EvalQuant

datasplitter:
  dataset_class: ChunkDataset
  dataset_root: "/vol/data/datasets/Omega/preprocessed_cloud"
  example_seconds: 2
  overlap_seconds: 1
  val_ratio: 0.1
  test_ratio: 0.1
  refresh_cache: false  # need to refresh if any datasplitter args change
  cache_dir: /vol/data/datasets/Omega/local_cache/preprocessed

dataloader:
  batch_size: 64
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

eval:
  accelerator: cuda
  future_steps: 10
  gen_seconds: 30
  gen_sampling: top_p
  channel_shape: [274]
  num_channels: 274
  temperature: 10.0
  top_p: 0.5
  ckpt_path: /vol/data/trainings/omega/gpt2megmix/lightning_logs/version_16/checkpoints/epoch=21-step=141746.ckpt