# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/gpt2megmix/model_visual.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/omega/gpt2megmix500ms/visual
resume_from: null

model_name: GPT2MEGMix
loss_name: CrossEntropy
eval_class: EvalQuant

datasplitter:
  dataset_class: ChunkDatasetSubset
  dataset_root: "/vol/data/datasets/Omega/preprocessed_cloud"
  example_seconds: 0.5
  overlap_seconds: 0.25
  val_ratio: 0.1
  test_ratio: 0.1
  refresh_cache: false  # need to refresh if any datasplitter args change
  cache_dir: /vol/data/datasets/Omega/local_cache/preprocessed500ms
  dataset_kwargs:
    fill_value: 127

dataloader:
  batch_size: 64
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

eval:
  accelerator: cuda
  future_steps: 10
  gen_seconds: 30
  gen_sampling: top_p
  channel_shape: [64]
  num_channels: 64
  temperature: 1.0
  top_p: 0.8
  ckpt_path: /vol/data/trainings/omega/gpt2megmix500ms/lightning_logs/version_21/checkpoints/last-checkpoint.ckpt