# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/gpt2megmix/model_mous.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/mous/1to50hz/gpt2megmix
resume_from: null

model_name: GPT2MEGMix
loss_name: CrossEntropy
eval_class: EvalQuant

datasplitter:
  dataset_class: ChunkDatasetCondition
  dataset_root: "/vol/data/datasets/MOUS/preprocessed1to50hz_cloud"
  example_seconds: 1.0
  overlap_seconds: 0.5
  val_ratio: 0.1
  test_ratio: 0.1
  refresh_cache: false  # need to refresh if any datasplitter args change
  cache_dir: /vol/data/datasets/MOUS/local_cache/preprocessed1to50hz
  dataset_kwargs:
    fill_value: 127

dataloader:
  batch_size: 64
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

eval:
  accelerator: cuda
  save_test_data: false
  use_test_dataset: true
  future_steps: 10
  unroll_steps: 1
  gen_seconds: 7200
  gen_sampling: top_p
  channel_shape: [275]
  num_channels: 275
  temperature: 1.0
  top_p: 0.8
  ckpt_path: /vol/data/trainings/mous/1to50hz/gpt2megmix/lightning_logs/version_10/checkpoints/best-checkpoint.ckpt