# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/gpt2megmix/model_single.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/gpt2megmix
resume_from: null

model_name: GPT2MEGMix
loss_name: CrossEntropy
eval_class: EvalQuant

datasplitter:
  dataset_class: ChunkDataset
  dataset_root: /vol/data/datasets/Omega/preprocessed
  example_seconds: 0.5
  overlap_seconds: 0.25
  val_ratio: 0.1
  test_ratio: 0.1

dataloader:
  batch_size: 64
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

eval:
  accelerator: cuda
  save_test_data: true
  future_steps: 10
  gen_seconds: 30
  gen_sampling: top_p
  channel_shape: [272]
  num_channels: 272
  temperature: 1.0
  top_p: 0.8
  ckpt_path: /vol/data/trainings/gpt2megmix/lightning_logs/version_7/checkpoints/last-checkpoint.ckpt