num_channels: 274
vocab_size: 256
d_model: 1644
num_layers: 8  # 12
channel_dropout_p: 0.0
quant_emb: 6  # 8
attn_type: standard
mlp_type: standard

attn_args:
  d_model: 1644
  nheads: 12  # 16
  dropout: 0.0
  rope: true

mlp_args:
  d_model: 1644
  # num_experts: 8
  # experts_per_token: 1