num_channels: 272
vocab_size: 256
d_model: 1632
num_layers: 12  # 12
channel_dropout_p: 0.0
quant_emb: 6  # 8
attn_type: standard
mlp_type: standard

attn_args:
  d_model: 1632
  nheads: 12  # 16
  dropout: 0.1
  rope: true

mlp_args:
  d_model: 1632
  # num_experts: 8
  # experts_per_token: 1