codebook_size: 32768  # 32768
embed_dim: 4  # 4, try higher
z_channels: 4  # 4
double_z: False
in_channels: 1
out_channels: 1
temporal_downsample_factor: 8  # 4
ch: 128  # 256
ch_mult: [1, 2, 2, 4]  # this is 8x reduction, [1, 2, 2, 4]
num_res_blocks: 2  # 2
attn_resolutions: [3]  # [3]
quantizer_revive_warmup_steps: 0
quantizer_revive_interval: 1
quantizer_revive_min_usage: 0.1
quantizer_track_usage: False
diversity_loss_weight: 0.01