model_config: configs/vqgpt2meg/tokenizer_omega_small.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/omega/2sub/1to50hz/emu3visionvq
resume_from: null

model_name: Emu3VisionVQGAN
loss_name: VQVAELoss

datasplitter:
  dataset_class: ChunkDatasetImageReconstruction
  dataset_root: /vol/data/datasets/Omega/preprocessed_1to50hz_cont_small
  example_seconds: 1.28
  overlap_seconds: 0.0
  val_ratio: 0.1
  test_ratio: 0.1
  dataset_kwargs:
    image_size: 32

dataloader:
  batch_size: 16
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

loss: {}

lightning:
  lr: 2.0e-4
  weight_decay: 0.01
  compile: false
  log_samples: false
  log_psd: False
  sfreq: 100
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 1.0e-6
    T_max: 100

trainer:
  max_epochs: 100
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  precision: 16-mixed
  gradient_clip_val: 10.0
