model_config: configs/vqgpt2meg/model_omega_small.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/omega/2sub/1to50hz/vqgpt2meg
resume_from: null

model_name: VQGPT2MEG
loss_name: CrossEntropyWithCodes

datasplitter:
  dataset_class: ChunkDatasetImageReconstruction
  dataset_root: /vol/data/datasets/Omega/preprocessed_1to50hz_cont_small
  example_seconds: 30
  overlap_seconds: 10
  val_ratio: 0.1
  test_ratio: 0.1
  dataset_kwargs:
    image_size: 32

dataloader:
  batch_size: 4
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

loss: {}

lightning:
  lr: 1.0e-3
  weight_decay: 0.01
  compile: false
  log_samples: false
  log_psd: False
  sfreq: 100
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 1.0e-5
    T_max: 100

trainer:
  max_epochs: 100
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  precision: 16-mixed
  gradient_clip_val: 10.0
