model_config: configs/vqgpt2meg/tokenizer_omega.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/omega/1to50hz_ss/emu3visionvq
resume_from: null

model_name: Emu3VisionVQ
loss_name: VQVAELoss

datasplitter:
  dataset_class: ChunkDatasetImageReconstruction
  dataset_root: "/vol/data/datasets/Omega/preprocessed1to50hz_ss_cloud"
  example_seconds: 50.0
  overlap_seconds: 5.0
  val_ratio: 0.1
  test_ratio: 0.1
  refresh_cache: false  # need to refresh if any datasplitter args change
  cache_dir: /vol/data/datasets/Omega/local_cache/preprocessed1to50hz_ss_50sec_cont

dataloader:
  batch_size: 64
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

loss: {}

lightning:
  lr: 1.0e-4
  weight_decay: 0.0
  compile: true
  log_samples: false
  log_psd: False
  sfreq: 100
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 1.0e-6
    T_max: 100

trainer:
  max_epochs: 100
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 200
  precision: 16-mixed
  gradient_clip_val: 10.0
