num_channels: 64
vocab_size: 256
d_model: 512
num_layers: 8  # 12
channel_dropout_p: 0.0
quant_emb: 8  # 8
attn_type: standard
mlp_type: standard

attn_args:
  d_model: 512
  nheads: 16  # 16
  dropout: 0.0
  rope: true

mlp_args:
  d_model: 512
  # num_experts: 8
  # experts_per_token: 1