num_channels: 275
vocab_size: 256
d_model: 2200
num_layers: 16  # 12
channel_dropout_p: 0.0
quant_emb: 8  # 8
attn_type: standard
mlp_type: standard

embedding_args:
  class_emb: 8
  num_classes: 6

attn_args:
  d_model: 2200
  nheads: 20  # 16
  dropout: 0.1
  rope: true

mlp_args:
  d_model: 2200
  # num_experts: 8
  # experts_per_token: 1