# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/gpt2megmix/model.yaml
augmentations: configs/augmentations.yaml

save_dir: trainings/omega/gpt2megmix
resume_from: null

model_name: GPT2MEGMix
loss_name: CrossEntropy

datasplitter:
  dataset_class: ChunkDataset
  dataset_root: /Users/richard/Datasets/Omega/preprocessed
  example_seconds: 2
  overlap_seconds: 1
  val_ratio: 0.1
  test_ratio: 0.1
  refresh_cache: true
  cache_dir: /Users/richard/Datasets/Omega/cloud_cache/preprocessed

dataloader:
  batch_size: 1
  num_workers: 0
  prefetch_factor: null
  pin_memory: false
  persistent_workers: false

loss:
  label_smoothing: 0.0
  l1: 0.0

lightning:
  lr: 1.0e-3
  weight_decay: 0.01
  compile: false
  log_samples: false
  log_psd: False
  sfreq: 200
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 1.0e-5
    T_max: 50

trainer:
  max_epochs: 50
  accelerator: mps
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 100
  gradient_clip_val: 10.0
