model_config: configs/vqgpt2meg/model_mous_small.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/mous/2sub/1to50hz_causal/vqgpt2meg
resume_from: null

model_name: VQGPT2MEG
loss_name: CrossEntropyWithCodes

datasplitter:
  dataset_class: ChunkDatasetImageCondition
  dataset_root: "/vol/data/datasets/MOUS/preprocessed_1to50hz_causal_cont"
  example_seconds: 1.0
  overlap_seconds: 0.5
  val_ratio: 0.33
  test_ratio: 0.0

dataloader:
  batch_size: 128
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

loss: {}

lightning:
  lr: 1.0e-4
  weight_decay: 0.0
  compile: true
  log_samples: false
  log_psd: False
  sfreq: 200
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 1.0e-6
    T_max: 100

trainer:
  max_epochs: 100
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 100
  precision: 16-mixed
  gradient_clip_val: 10.0