# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/models/gpt2meg.yaml
augmentations: configs/augmentations.yaml

save_dir: trainings/gpt2meg
resume_from: null

model_name: GPT2MEG
loss_name: CrossEntropy

datasplitter:
  dataset_root: /Users/richard/Datasets/Omega/preprocessed
  example_seconds: 5
  overlap_seconds: 0
  val_ratio: 0.1
  test_ratio: 0.1

dataloader:
  batch_size: 1
  shuffle: true
  num_workers: 0
  prefetch_factor: null
  pin_memory: false
  persistent_workers: false

loss:
  label_smoothing: 0.0
  l1: 0.0

lightning:
  lr: 0.001
  weight_decay: 0.0
  compile: false

trainer:
  max_epochs: 100
  accelerator: mps
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 50

eval:
  future_steps: 2
  gen_seconds: 60
  gen_sampling: top-p
  temperature: 0.5
  top_p: 0.8
  ckpt_path: trainings/gpt2meg/lightning_logs/version_8/epoch=8-step=4257.ckpt
