model_config: configs/cosmos/model.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/omega/2sub/1to50hz/cosmos
resume_from: null

model_name: CosmosTokenizer
loss_name: CosmosTokenizerLoss

datasplitter:
  dataset_class: ChunkDatasetImageReconstruction
  dataset_root: /vol/data/datasets/Omega/preprocessed_1to50hz_cont_small
  example_seconds: 2.56
  overlap_seconds: 0.0
  val_ratio: 0.1
  test_ratio: 0.1
  dataset_kwargs:
    image_size: 32

dataloader:
  batch_size: 16
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

loss:
  codebook_size: 1600
  recon_weight: 1.0
  quant_weight: 1.0

lightning:
  lr: 1.0e-4
  weight_decay: 0.01  # 0.01
  compile: false
  sfreq: 100
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 1.0e-6
    T_max: 100

trainer:
  max_epochs: 100
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 20
  # precision: 16-mixed
  gradient_clip_val: 10.0
