dataloader:
  batch_size: 2
  num_workers: 16
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 4
datasplitter:
  cache_dir: /vol/data/datasets/omega/full/cache/1to50hz_ss_cont_57.6
  dataset_class: ChunkDatasetReconstruction
  dataset_root: /vol/data/datasets/omega/full/1to50hz_ss_cont
  example_seconds: 57.6
  overlap_seconds: 5
  refresh_cache: false
  test_ratio: 0.1
  val_ratio: 0.1
eval_runner:
  ckpt_path: /vol/data/trainings/omega/1to50hz_ss/vqflatgpt/qwen2p5_flat/logs/version_2/checkpoints/best-checkpoint-epoch00013.ckpt
  enabled: true
  epoch: 13
  generate:
    enabled: true
    divergence_window_seconds: 1.0  # this is the stride
    kv_overlap: 3200
    num_runs: 20
    seconds: 115.2
    top_p: 1.0
  max_batches: 10
  modal_app: ephys-gpt
  modal_function: runevals
  num_examples: 0
  step: 35660
  use_modal: true
  version: 2
lightning:
  lr: 0.0001
  lr_scheduler:
    T_max: 100
    class_name: CosineAnnealingLR
    eta_min: 1.0e-05
  weight_decay: 0.1
loss_name: CrossEntropyWithCodes
model_config: configs/vqflatgpt/qwen2p5/model.yaml
model_name: FlatGPTEmbedsRVQ
resume_from: null
save_dir: /vol/data/trainings/omega/1to50hz_ss/vqflatgpt/qwen2p5_flat
trainer:
  accelerator: cuda
  check_val_every_n_epoch: 1
  checkpoint_cadence_epochs: 1
  default_root_dir: /vol/data/trainings/omega/1to50hz_ss/vqflatgpt/qwen2p5_flat
  gradient_clip_val: 1.0
  log_every_n_steps: 100
  max_epochs: 100
  precision: bf16-mixed