ddconfig:
  double_z: false
  z_channels: 64
  resolution: 32
  in_channels: 1
  out_ch: 1
  ch: 64
  ch_mult: [1, 2, 2]
  num_res_blocks: 2
  attn_resolutions: [8]
  dropout: 0.0

n_embed: 1024
embed_dim: 64
# IndexPropagationQuantize args
beta: 0.25
use_entropy_loss: false
cosine_similarity: false
entropy_temperature: 0.01
sample_minimization_weight: 1.0
batch_maximization_weight: 1.0
