model_config: configs/brainomni/model.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/omega/2sub/1to50hz_ss/brainomni
resume_from: null

model_name: BrainOmniCausalForecast
loss_name: BrainOmniCausalForecastLoss

datasplitter:
  dataset_class: ChunkDatasetReconstruction
  dataset_root: /vol/data/datasets/Omega/preprocessed_1to50hz_ss_cont
  example_seconds: 30
  overlap_seconds: 10
  val_ratio: 0.1
  test_ratio: 0.1

dataloader:
  batch_size: 4
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

loss: {}

lightning:
  lr: 1.0e-4
  weight_decay: 0.01
  compile: false
  sfreq: 100
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 1.0e-6
    T_max: 100

trainer:
  max_epochs: 100
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 20
  precision: 16-mixed
  gradient_clip_val: 10.0
