dataloader:
  batch_size: 128
  num_workers: 16
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 4
datasplitter:
  cache_dir: /vol/data/datasets/omega/full/cache/1to50hz_ss_10s
  dataset_class: ChunkDataset3D
  dataset_root: /vol/data/datasets/omega/full/1to50hz_ss
  example_seconds: 10
  overlap_seconds: 5
  refresh_cache: false
  test_ratio: 0.45
  val_ratio: 0.45
eval_runner:
  ckpt_path: /vol/data/trainings/omega/1to50hz_ss/flatgpt/channelmix/logs/version_20/checkpoints/best-checkpoint-epoch00025.ckpt
  enabled: true
  epoch: 26
  generate:
    enabled: true
    kv_overlap: 10
    num_runs: 3
    seconds: 30
    top_p: 1.0
    temperature: 1.0
    strategy: argmax
  max_batches: 1000
  modal_app: ephys-gpt
  modal_function: runevals
  mu: 255
  num_examples: 0
  step: 900
  use_modal: true
  version: 20
lightning:
  compile: false
  lr: 0.001
  lr_scheduler:
    T_max: 100
    class_name: CosineAnnealingLR
    eta_min: 0.0002
  weight_decay: 0.1
loss_name: CrossEntropyWithCodes
model_config: configs/flatgpt/channelmix/model.yaml
model_name: FlatGPTMix
resume_from: null
save_dir: /vol/data/trainings/omega/1to50hz_ss/flatgpt/channelmix
trainer:
  accelerator: cuda
  check_val_every_n_epoch: 1
  checkpoint_cadence_epochs: 5
  default_root_dir: /vol/data/trainings/omega/1to50hz_ss/flatgpt/channelmix
  gradient_clip_val: 1.0
  log_every_n_steps: 20
  max_epochs: 100
  precision: bf16-mixed