# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/gpt2meg_trf/model_mous68.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/mous/1to50hz_ss/gpt2meg_trf
resume_from: null

model_name: GPT2MEG_Trf
loss_name: CrossEntropy
eval_class: EvalQuant

datasplitter:
  dataset_class: ChunkDatasetCondition
  dataset_root: "/vol/data/datasets/MOUS/preprocessed1to50hz_ss_cloud"
  example_seconds: 0.5
  overlap_seconds: 0.0
  val_ratio: 0.1
  test_ratio: 0.1
  refresh_cache: false  # need to refresh if any datasplitter args change
  cache_dir: /vol/data/datasets/MOUS/local_cache/preprocessed1to50hz_ss_500ms_0overlap
  dataset_kwargs:
    fill_value: 127

dataloader:
  batch_size: 64
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

eval:
  accelerator: cuda
  save_test_data: false
  use_test_dataset: true
  future_steps: 10
  unroll_steps: 100
  gen_seconds: 600
  gen_sampling: top_p
  channel_shape: [68]
  num_channels: 68
  temperature: 1.0
  top_p: 0.8
  ckpt_path: /vol/data/trainings/mous/1to50hz_ss/gpt2meg_trf/lightning_logs/version_2/checkpoints/best-checkpoint.ckpt