in_channels: 272
head_channels: 32
quant_levels: 256
quant_emb: 32
kernel_size: 2
dilations: [1, 2, 4, 8, 16, 32, 64, 128, 1, 2, 4, 8, 16, 32, 64, 128]
residual_channels: 32
dilation_channels: 32
skip_channels: 128
cond_channels: null