trf_class: SmoLLM3
tok_class: BPETokenizer
hidden_size: 1024
vocab_size: 131072
input_shape: [1000, 68, 1]  # T, H, W

tok_args:
  tokenizer_path: /vol/data/datasets/Omega/preprocessed_1to50hz_ss_64bit_txt
  group_size: 10

trf_args:
  intermediate_size: 5504
  num_hidden_layers: 8
  num_attention_heads: 8
  num_key_value_heads: 2
  attention_dropout: 0.1

  max_position_embeddings: 68000
  pad_token_id: 0
  max_window_layers: 28
  model_type: smollm3
  no_rope_layer_interval: 4
  rope_theta: 1000000.0

  no_rope_layers: [
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    0
  ]