# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/models/ntd.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/ntd
resume_from: null

model_name: NTD
loss_name: NTDLoss

datasplitter:
  dataset_class: ChunkDatasetReconstruction
  dataset_root: /vol/data/datasets/Omega/preprocessed_cont
  example_seconds: 2
  overlap_seconds: 1
  val_ratio: 0.1
  test_ratio: 0.1

dataloader:
  batch_size: 128
  num_workers: 8
  prefetch_factor: 2
  pin_memory: true
  persistent_workers: true

loss: {}

lightning:
  lr: 0.001
  weight_decay: 0.01
  compile: true
  log_samples: false
  log_psd: true
  sfreq: 200

trainer:
  max_epochs: 10000
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 10
  log_every_n_steps: 10
  gradient_clip_val: 1.0
  precision: 16-mixed
