# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/gpt2meg/model_mous_small.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/mous/small/100hz500ms/gpt2meg
resume_from: null

model_name: GPT2MEG
loss_name: CrossEntropy

datasplitter:
  dataset_class: ChunkDatasetCondition
  dataset_root: "/vol/data/datasets/MOUS/preprocessed100hz"
  example_seconds: 1.0
  overlap_seconds: 0.5
  val_ratio: 0.33
  test_ratio: 0.33

dataloader:
  batch_size: 64  # 64
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

loss:
  label_smoothing: 0.0
  l1: 0.0

lightning:
  lr: 2.0e-4
  weight_decay: 0.0
  compile: true
  log_samples: false
  log_psd: False
  sfreq: 200
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 2.0e-6
    T_max: 100

trainer:
  max_epochs: 100
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 25
  precision: 16-mixed
  gradient_clip_val: 10.0
