# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/stgpt2meg/model_convblock.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/omega/2sub/1to50hz/stgpt2meg/convblock
resume_from: null

model_name: STGPT2MEG
loss_name: CrossEntropy
eval_class: EvalQuant

datasplitter:
  dataset_class: ChunkDataset
  dataset_root: "/vol/data/datasets/Omega/preprocessed_1to50hz_small"
  example_seconds: 2.0
  overlap_seconds: 1.0
  val_ratio: 0.1
  test_ratio: 0.1
  dataset_kwargs:
    fill_value: 127
    image_size: 28
    tmp_dir: "tmp"

dataloader:
  batch_size: 64
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

eval:
  dtype: float32
  accelerator: cuda
  save_test_data: true
  use_test_dataset: false
  future_steps: 10
  unroll_steps: 1
  gen_seconds: 60
  gen_sampling: top_p
  channel_shape: [272]
  num_channels: 272
  temperature: 1.0
  top_p: 0.8
  ckpt_path: /vol/data/trainings/omega/2sub/1to50hz/stgpt2meg/convblock/lightning_logs/version_12/checkpoints/best-checkpoint.ckpt