num_channels: 274
vocab_size: 256
d_model: 256
layers: 8
trf_block: STGPTBlock  # STGPTBlock, STGPTBlockParallel, STBlock

trf_args:
  attn_type: standard
  mlp_type: standard

  attn_args:
    d_model: 256
    nheads: 8
    dropout: 0.0
    rope: true

  mlp_args:
    d_model: 256
    # num_experts: 4
    # experts_per_token: 2