# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/stgpt2meg/model_convblock.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/omega/2sub/1to50hz/stgpt2meg/convblock
resume_from: null

model_name: STGPT2MEG
loss_name: CrossEntropy

datasplitter:
  dataset_class: ChunkDataset
  dataset_root: "/vol/data/datasets/Omega/preprocessed_1to50hz_small"
  example_seconds: 2.0
  overlap_seconds: 1.0
  val_ratio: 0.1
  test_ratio: 0.1
  dataset_kwargs:
    fill_value: 127
    image_size: 28
    tmp_dir: "tmp"

dataloader:
  batch_size: 8  # 512
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

loss:
  label_smoothing: 0.0
  l1: 0.0

lightning:
  lr: 5.0e-5
  weight_decay: 0.01
  compile: true
  log_samples: false
  log_psd: False
  sfreq: 200
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 5.0e-7
    T_max: 200

trainer:
  max_epochs: 200
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 200
  # precision: 16-mixed
  gradient_clip_val: 10.0
