encoder:
  double_z: false
  z_channels: 5
  in_channels: 1
  out_ch: 1
  ch: 64  # 128
  ch_mult: [1, 2, 4, 4]
  tempo_ds: [0, 1, 2]
  tempo_us: [1, 2, 3]
  time_downsample_factor: 8
  num_res_blocks: 2
  dropout: 0.0
  use_checkpoint: false
  init_pad_mode: replicate
  norm_type: layernorm  # layernorm, groupnorm
  interpolation_mode: trilinear  # nearest, trilinear
  fix_encoder: false  # if True, fix it without updating params
  fix_decoder: false  # if True, fix it without updating params

regularizer:
  levels: [8, 8, 8, 8, 8]  # codebook size: 8*8*8*8=4096
  entropy_loss_weight: 0.1
  entropy_loss_annealing_steps: 20
  entropy_loss_annealing_factor: 3
  commitment_loss_weight: 0.25
