in_channels: 1
image_size: [32, 32]
spatial_levels: 2  # increase for higher res
spatial_steps_per_level: 4
spatial_hidden: 256
emission_levels: 2
emission_steps_per_level: 4
emission_hidden: 256
cond_dim: 512
temporal_levels: 8  # strides: 1,2,4,8,16,32,64
temporal_state_dim: 512
rollout_prob: 0.0