num_channels: 274
num_layers: 8
vocab_size: 256
d_model: 256
quant_emb: 256
attn_type: standard
mlp_type: standard

embedding_args:
  channel_emb: 256

attn_args:
  d_model: 0
  nheads: 8
  dropout: 0.0
  rope: true

mlp_args:
  d_model: 0
  # num_experts: 4
  # experts_per_token: 2