num_channels: 272
num_layers: 12
vocab_size: 256
d_model: 128
quant_emb: 128
attn_type: standard
mlp_type: standard

embedding_args:
  channel_emb: 128

attn_args:
  d_model: 0
  nheads: 16
  dropout: 0.0
  rope: true

mlp_args:
  d_model: 0
  # num_experts: 4
  # experts_per_token: 2