# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/gpt2meg_trf/model.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/gpt2meg_trf
resume_from: null

model_name: GPT2MEG_Trf
loss_name: CrossEntropy

datasplitter:
  dataset_class: ChunkDataset
  dataset_root: "/vol/data/datasets/Omega/preprocessed"
  example_seconds: 2
  overlap_seconds: 1
  val_ratio: 0.1
  test_ratio: 0.1
  # dataset_kwargs:
  #   quant_levels: 256
  #   max_val: 5.0

dataloader:
  batch_size: 4
  num_workers: 16
  prefetch_factor: 2
  pin_memory: true
  persistent_workers: true

loss:
  label_smoothing: 0.0
  l1: 0.0

lightning:
  lr: 1.0e-4
  weight_decay: 0.0
  compile: true
  log_samples: false
  log_psd: False
  sfreq: 200
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 1.0e-6
    T_max: 50

trainer:
  max_epochs: 50
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
  precision: 16-mixed
  gradient_clip_val: 1.0
