window_length: 256  # paper uses 2 seconds, we use 2.56s
n_filters: 64  # 32
ratios: [2, 2, 2, 2]  # 8,4,2
kernel_size: 5  # 5
last_kernel_size: 5  # 5
n_dim: 3072  # 256
n_neuro: 4  # 16
n_head: 16  # 4

codebook_size: 32768  # 512
codebook_dim: 3072  # 256
num_quantizers: 8  # 4

rotation_trick: true  # true
mask_ratio: 0.0  # 0.25, lower value lowers loss
dropout: 0.0  # 0.0
noise_std: 0.0  # 0.1
normalize: false  # true
num_sensors: 68