window_length: 128  # paper uses 2 seconds, we use 1.28s
n_filters: 32  # 32
ratios: [2, 2, 2]  # 8,4,2
kernel_size: 5  # 5
last_kernel_size: 5  # 5
n_dim: 256  # 256
n_neuro: 16  # 16
n_head: 4  # 4

codebook_size: 512  # 512
codebook_dim: 256  # 256
num_quantizers: 4  # 4

sensor_space: "sensor"  # source or sensor
shuffle_channels: true  # shuffle channels