save_dir: trainings/omega/1to50hz/brainomni_tok/
resume_from: null

model_name: BrainOmniCausalTokenizer
loss_name: BrainOmniCausalTokenizerLoss
model_config: configs/brainomni_tok/tokenizer_small.yaml

datasplitter:
  dataset_class: ChunkDatasetSensor3D
  dataset_root: /Users/richard/Datasets/Omega/preprocessed_raw2
  example_seconds: 2.56
  overlap_seconds: 0.0
  val_ratio: 0.1
  test_ratio: 0.1

dataloader:
  batch_size: 2
  num_workers: 0
  prefetch_factor: null
  pin_memory: false
  persistent_workers: false

lightning:
  lr: 2.0e-4
  weight_decay: 0.0
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 1.0e-4
    T_max: 200

trainer:
  tune_batch_size: false
  max_epochs: 200
  accelerator: mps
  check_val_every_n_epoch: 1
  checkpoint_cadence_epochs: 1
  log_every_n_steps: 10
