# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/models/stgpt2meg.yaml
augmentations: configs/augmentations.yaml

save_dir: trainings/stgpt2meg/modal
resume_from: null

model_name: STGPT2MEG
loss_name: CrossEntropy
eval_class: EvalQuant

datasplitter:
  dataset_root: "/Users/richard/Datasets/Omega/preprocessed"
  example_seconds: 2
  overlap_seconds: 1
  val_ratio: 0.1
  test_ratio: 0.1

dataloader:
  batch_size: 1
  num_workers: 0
  prefetch_factor: null
  pin_memory: false
  pin_memory_device: ""

eval:
  accelerator: mps
  future_steps: 10
  gen_seconds: 30
  gen_sampling: top_p
  channel_shape: [272]
  num_channels: 272
  temperature: 1.0
  top_p: 0.8
  ckpt_path: trainings/stgpt2meg/modal/epoch=1-step=1890.ckpt