model_config: configs/models/vqgpt2meg.yaml
augmentations: configs/augmentations.yaml

save_dir: trainings/vqgpt2meg
resume_from: null

model_name: VQGPT2MEG
loss_name: CrossEntropyWithCodes

datasplitter:
  dataset_class: ChunkDatasetImage
  dataset_root: /Users/richard/Datasets/Omega/preprocessed_cont
  example_seconds: 1
  overlap_seconds: 0
  val_ratio: 0.1
  test_ratio: 0.1

dataloader:
  batch_size: 1
  num_workers: 0
  prefetch_factor: null
  pin_memory: false
  persistent_workers: false

loss: {}

lightning:
  lr: 0.001
  weight_decay: 0.0
  compile: false
  log_samples: false
  log_psd: false
  sfreq: 200

trainer:
  max_epochs: 1000
  accelerator: mps
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 100
  log_every_n_steps: 10
  overfit_batches: 1
  gradient_clip_val: 1.0