quant_levels: 256
quant_emb: 32
kernel_size: 2
dilations: [1, 2, 4, 8, 16, 32, 64, 1, 2, 4, 8, 16, 32, 64]  # Receptive field = 1 + sum(dilations) = 1 + 254 = 255 samples
residual_channels: 32
dilation_channels: 32
head_channels: 32
skip_channels: 64
spatial_kernel_size: 5
spatial_dilation: 1
cond_channels: null