quant_levels: 256
quant_emb: 128
kernel_size: 2
dilations: [1, 2, 4, 8, 16, 32, 1, 2, 4, 8, 16, 32]  # Receptive field = 1 + sum(dilations) = 1 + 254 = 255 samples
residual_channels: 128
dilation_channels: 128
head_channels: 256
skip_channels: 256
spatial_kernel_size: 3
spatial_dilation: 2
cond_channels: null