# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/tasa3d/model.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/tasa3d
resume_from: null

model_name: TASA3D
loss_name: CrossEntropy
eval_class: EvalQuant

datasplitter:
  dataset_class: ChunkDatasetImageQuantized
  dataset_root: /vol/data/datasets/Omega/preprocessed
  example_seconds: 2
  overlap_seconds: 1
  val_ratio: 0.1
  test_ratio: 0.1

dataloader:
  batch_size: 64
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

eval:
  accelerator: cuda
  future_steps: 10
  gen_seconds: 30
  gen_sampling: top_p
  channel_shape: [272]
  num_channels: 272
  temperature: 1.0
  top_p: 0.8
  ckpt_path: /vol/data/trainings/tasa3d/lightning_logs/version_5/checkpoints/best-checkpoint.ckpt