input_hw: [32, 32]
emb_dim: 12  # embedding dim; d_model will be emb_dim * 2**num_down * spatial tokens
depth: 8  # number of TASA3DBlock
num_down: 4  # reduce spatial size by 2^num_down
channel_grow: 2  # multiply channels by channel_grow each downstage
heads: 12
drop: 0.1
rope: true