# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/tasa3d/model_mous.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/mous/tasa3d
resume_from: null

model_name: TASA3D
loss_name: CrossEntropy

datasplitter:
  dataset_class: ChunkDatasetImageQuantized
  dataset_root: "/vol/data/datasets/MOUS/preprocessed_cloud"
  example_seconds: 0.5
  overlap_seconds: 0.25
  val_ratio: 0.1
  test_ratio: 0.1
  refresh_cache: false  # need to refresh if any datasplitter args change
  cache_dir: /vol/data/datasets/MOUS/local_cache/preprocessed500ms
  dataset_kwargs:
    fill_value: 127

dataloader:
  batch_size: 96  # 64
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

loss:
  label_smoothing: 0.0
  l1: 0.0

lightning:
  lr: 1.0e-5
  weight_decay: 0.0
  compile: true
  log_samples: false
  log_psd: False
  sfreq: 200
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 1.0e-7
    T_max: 100

trainer:
  max_epochs: 100
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 2000
  precision: 16-mixed
  gradient_clip_val: 5.0
