# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/megformer/model.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/omega/megformer
resume_from: null

model_name: MEGFormer
loss_name: NLL
eval_class: EvalFlow

datasplitter:
  dataset_class: ChunkDatasetImage
  dataset_root: "/vol/data/datasets/Omega/preprocessed_cont_cloud"
  example_seconds: 0.5
  overlap_seconds: 0.25
  val_ratio: 0.1
  test_ratio: 0.1
  refresh_cache: false  # need to refresh if any datasplitter args change
  cache_dir: /vol/data/datasets/Omega/local_cache/preprocessed_cont_500ms

dataloader:
  batch_size: 64
  num_workers: 0
  prefetch_factor: null
  pin_memory: true
  persistent_workers: false

eval:
  accelerator: cuda
  future_steps: 10
  gen_seconds: 30
  gen_sampling: top_p
  channel_shape: [274]
  num_channels: 274
  temperature: 1.0
  top_p: 0.8
  ckpt_path: /vol/data/trainings/omega/megformer/lightning_logs/version_2/checkpoints/epoch-epoch=03.ckpt