# Data loader parameters
# example_seconds and overlap_seconds refer to the raw signal duration for each example
# expressed in seconds

# Augmentations are optional and can be enabled by setting parameters

# Separate model configuration file
model_config: configs/ntd/model.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/omega/2sub/1to50hz_ss/ntd/train_data
resume_from: null

model_name: NTD
loss_name: NTDLoss
eval_class: EvalDiffusion

datasplitter:
  dataset_class: ChunkDatasetReconstruction
  dataset_root: /vol/data/datasets/Omega/preprocessed_1to50hz_ss_cont
  example_seconds: 2.0
  overlap_seconds: 1.0
  val_ratio: 0.1
  test_ratio: 0.1

dataloader:
  batch_size: 64
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

eval:
  accelerator: cuda
  save_test_data: true
  use_test_dataset: false
  future_steps: 10
  unroll_steps: 5
  gen_seconds: 60
  gen_sampling: top_p
  channel_shape: [68]
  num_channels: 68
  temperature: 1.0
  top_p: 0.8
  ckpt_path: /vol/data/trainings/omega/2sub/1to50hz_ss/ntd/lightning_logs/version_4/checkpoints/best-checkpoint.ckpt

