signal_length: 1024
signal_channel: 68
mask_channel: 1  # used for forecasting
cond_dim: 0
p_forecast: 0.5

diffusion_time_steps: 500
schedule: linear
start_beta: 0.0001
end_beta: 0.03
ou_sigma2: 2.0  # 1.0
ou_ell: 10.0  # 10.0
noise_process: white

net_hidden_channel: 32  # 8
net_in_kernel_size: 1
net_out_kernel_size: 1
net_slconv_kernel_size: 65  # 65
net_num_scales: 4  # 1
net_num_blocks: 12  # 3
net_num_off_diag: 8  # 8
net_use_pos_emb: True
net_padding_mode: circular
net_use_fft_conv: False
