model_config: configs/megformer/model_mous.yaml
augmentations: configs/local/augmentations.yaml

save_dir: /vol/data/trainings/mous/2sub/1to50hz_causal/megformer
resume_from: null

model_name: MEGFormer
loss_name: NLL

datasplitter:
  dataset_class: ChunkDatasetImageReconstruction
  dataset_root: "/vol/data/datasets/MOUS/preprocessed_1to50hz_causal_cont"
  example_seconds: 1.0
  overlap_seconds: 0.5
  val_ratio: 0.33
  test_ratio: 0.0
  dataset_kwargs:
    has_condition: true

dataloader:
  batch_size: 128  # 128
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

loss: {}

lightning:
  lr: 2.0e-4
  weight_decay: 0.01
  compile: true
  log_samples: false
  log_psd: False
  sfreq: 200
  lr_scheduler:
    class_name: CosineAnnealingLR
    eta_min: 2.0e-6
    T_max: 100

trainer:
  max_epochs: 100
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  # overfit_batches: 1
  check_val_every_n_epoch: 1
  log_every_n_steps: 20
  precision: 16-mixed
  gradient_clip_val: 10.0
