dataloader:
  batch_size: 1
  num_workers: 16
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 4
datasplitter:
  cache_dir: /vol/data/datasets/omega/full/cache/1to50hz_ss_2s
  dataset_class: ChunkDataset3D
  dataset_root: /vol/data/datasets/omega/full/1to50hz_ss
  example_seconds: 2
  overlap_seconds: 1
  refresh_cache: false
  test_ratio: 0.1
  val_ratio: 0.1
eval_runner:
  ckpt_path: /vol/data/trainings/omega/1to50hz_ss/flatgpt/qwen/logs/version_1/checkpoints/last-checkpoint-epoch00005.ckpt
  enabled: true
  epoch: 6
  generate:
    enabled: true
    kv_overlap: 680
    num_runs: 2
    seconds: 10
    top_p: 1.0  # should try 0.8
  max_batches: 1000
  modal_app: ephys-gpt
  modal_function: runevals
  mu: 255
  num_examples: 0
  step: 29935
  use_modal: true
  version: 1
lightning:
  compile: false
  lr: 0.0002
  lr_scheduler:
    T_max: 100
    class_name: CosineAnnealingLR
    eta_min: 2.0e-05
  weight_decay: 0.1
loss_name: CrossEntropyWithCodes
model_config: configs/flatgpt/qwen/model_long.yaml
model_name: FlatGPT
resume_from: null
save_dir: /vol/data/trainings/omega/1to50hz_ss/flatgpt/qwen
trainer:
  accelerator: cuda
  check_val_every_n_epoch: 1
  checkpoint_cadence_epochs: 1
  default_root_dir: /vol/data/trainings/omega/1to50hz_ss/flatgpt/qwen
  gradient_clip_val: 1.0
  log_every_n_steps: 1000
  max_epochs: 100
  precision: bf16-mixed