trf_class: Qwen2_5_Video
hidden_size: 1024
vocab_size: 256
input_shape: [200, 68, 1]  # T, H, W

trf_args:
  intermediate_size: 5504
  num_hidden_layers: 18  # 36 in 3B model
  num_attention_heads: 8
  num_key_value_heads: 2
  attention_dropout: 0.0

  layout_path: /vol/data/datasets/mne_data/roi_layout_2d.npy
  
  max_position_embeddings: 16384  # should be higher than T' x H' x W'
  rope_theta: 1000000.0
  rope_scaling:  # can experiment with different types
    type: mrope  # default
    # mrope_section: 20  # should be hidden_size / attention_heads // 6
    mrope_section: [16, 24, 24]

  use_cache: False