model_config: configs/flatgpt/model_smollm_embeds.yaml

save_dir: /vol/data/trainings/omega/2sub/1to50hz_ss/flatgpt/smollm
resume_from: null

model_name: FlatGPTEmbeds
loss_name: CrossEntropyWithCodes
eval_class: EvalFlat

datasplitter:
  dataset_class: ChunkDataset3D
  dataset_root: /vol/data/datasets/Omega/preprocessed_1to50hz_ss_small
  example_seconds: 10
  overlap_seconds: 0
  val_ratio: 0.1
  test_ratio: 0.1

dataloader:
  batch_size: 1
  pin_memory: true

eval_runner:
  ckpt_path: /vol/data/trainings/omega/2sub/1to50hz_ss/flatgpt/smollm/lightning_logs/version_18/checkpoints/best-checkpoint.ckpt
  enabled: true
  epoch: 8
  mu: 255
  generate:
    enabled: true
    kv_overlap: 680
    seconds: 10
    top_p: 0.8
  max_batches: 1
  modal_app: ephys-gpt
  modal_function: runevals
  num_examples: 0
  step: null
  use_modal: true
  version: 18
