model_config: configs/vqvae/model.yaml
augmentations: configs/augmentations.yaml

save_dir: /vol/data/trainings/omega/2sub/1to50hz_ss/vqvae
resume_from: null

model_name: MLPVQVAE
loss_name: VQVAEHF

datasplitter:
  dataset_class: ChunkDatasetReconstruction
  dataset_root: /vol/data/datasets/Omega/preprocessed_1to50hz_ss_cont
  example_seconds: 1.0
  overlap_seconds: 0.0
  val_ratio: 0.1
  test_ratio: 0.1
  dataset_kwargs:
    transpose: true

dataloader:
  batch_size: 32
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

loss: {}

lightning:
  lr: 1.0e-3
  weight_decay: 0.0
  compile: false
  sfreq: 200
  # lr_scheduler:
  #   class_name: CosineAnnealingLR
  #   eta_min: 1.0e-4
  #   T_max: 100

trainer:
  max_epochs: 200
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 20
  # overfit_batches: 1
  # precision: bf16-mixed
  # gradient_clip_val: 10.0
