in_channels: 306
hidden_channels: [256, 256]
kernels: [7, 7]
strides: [2, 2]
num_classes: 39
lstm_num_layers: 2
conv_dropout: 0.0
channel_dropout_p: 0.0
lstm_dropout: 0.0
head_dropout: 0.0
norm: group
gn_groups: 16
attn_hidden: 128
attn_type: standard
mlp_type: moe
num_trf_blocks: 1
pooling: last  # last or attn

attn_args:
  d_model: 256
  nheads: 8
  dropout: 0.0

mlp_args:
  d_model: 256
  num_experts: 8
  experts_per_token: 4
