model_config: configs/cnnlstm/model.yaml
augmentations: configs/cnnlstm/augs.yaml

save_dir: /vol/data/trainings/cnnlstm # trainings/cnnlstm 
resume_from: null

model_name: CNNLSTM
loss_name: CrossEntropy
dataset_name: libribrain

datasplitter:
  dataset_class: GroupedDatasetAugmented
  dataset_root: /vol/data/LibriBrain  # /Users/richard/Datasets/LibriBrain
  grouped_samples_std: 0

dataloader:
  batch_size: 512
  num_workers: 32
  prefetch_factor: 2
  pin_memory: true
  persistent_workers: true

loss:
  label_smoothing: 0.0
  l1: 0.0

lightning:
  lr: 0.001
  weight_decay: 0.0
  compile: true
  log_samples: false
  log_psd: false
  sfreq: 200

trainer:
  max_epochs: 1000
  accelerator: cuda
  profiler: null
  fast_dev_run: false
  check_val_every_n_epoch: 1
  log_every_n_steps: 20
  precision: 16-mixed
